name = "日常"

[[pairs]]
civilian = "牙刷"
undercover = "梳子"

[[pairs]]
civilian = "毛巾"
undercover = "浴巾"

[[pairs]]
civilian = "雨伞"
undercover = "雨衣"

[[pairs]]
civilian = "拖鞋"
undercover = "运动鞋"

[[pairs]]
civilian = "牙膏"
undercover = "洗发水"

[[pairs]]
civilian = "脸盆"
undercover = "水桶"

[[pairs]]
civilian = "枕头"
undercover = "被子"

[[pairs]]
civilian = "肥皂"
undercover = "洗手液"

[[pairs]]
civilian = "抹布"
undercover = "海绵"

[[pairs]]
civilian = "2B铅笔"
undercover = "自动铅笔"

[[pairs]]
civilian = "橡皮"
undercover = "修正带"

[[pairs]]
civilian = "尺子"
undercover = "三角尺"

[[pairs]]
civilian = "书包"
undercover = "文具盒"

[[pairs]]
civilian = "圆珠笔"
undercover = "中性笔"

[[pairs]]
civilian = "卷笔刀"
undercover = "削笔刀"

[[pairs]]
civilian = "胶水"
undercover = "双面胶"

[[pairs]]
civilian = "作业本"
undercover = "草稿本"

[[pairs]]
civilian = "白天"
undercover = "黑夜"

[[pairs]]
civilian = "生日"
undercover = "纪念日"

[[pairs]]
civilian = "开学第一天"
undercover = "死期"

[[pairs]]
civilian = "早上"
undercover = "清晨"

[[pairs]]
civilian = "未来"
undercover = "明天"

[[pairs]]
civilian = "本命年"
undercover = "幸运日"

[[pairs]]
civilian = "板擦"
undercover = "白板"

[[pairs]]
civilian = "自习室"
undercover = "图书馆"

[[pairs]]
civilian = "操场"
undercover = "体育课"

[[pairs]]
civilian = "草稿本"
undercover = "练习册"

[[pairs]]
civilian = "副班主任"
undercover = "任课老师"

[[pairs]]
civilian = "升旗仪式"
undercover = "班会"

[[pairs]]
civilian = "校服"
undercover = "制服"

[[pairs]]
civilian = "校长"
undercover = "年级主任"

[[pairs]]
civilian = "老师"
undercover = "宿管"

[[pairs]]
civilian = "警察"
undercover = "军人"

[[pairs]]
civilian = "厨师"
undercover = "面包师"

[[pairs]]
civilian = "空军"
undercover = "飞行员"

[[pairs]]
civilian = "画家"
undercover = "小说家"

[[pairs]]
civilian = "花匠"
undercover = "园丁"

[[pairs]]
civilian = "新闻记者"
undercover = "主持人"

[[pairs]]
civilian = "蜡像师"
undercover = "雕刻家"

[[pairs]]
civilian = "理发师"
undercover = "化妆师"

[[pairs]]
civilian = "快递员"
undercover = "外卖员"

[[pairs]]
civilian = "律师"
undercover = "辩论家"

[[pairs]]
civilian = "玩具商"
undercover = "古董商"

[[pairs]]
civilian = "飞机"
undercover = "高铁"

[[pairs]]
civilian = "地铁"
undercover = "公交"

[[pairs]]
civilian = "自行车"
undercover = "电动车"

[[pairs]]
civilian = "出租车"
undercover = "网约车"

[[pairs]]
civilian = "轮船"
undercover = "游艇"

[[pairs]]
civilian = "火车"
undercover = "动车"

[[pairs]]
civilian = "摩托车"
undercover = "老头乐"

[[pairs]]
civilian = "校车"
undercover = "大巴"

[[pairs]]
civilian = "缆车"
undercover = "观光车"

[[pairs]]
civilian = "三轮车"
undercover = "手推车"
