name = "简单易懂"

[[pairs]]
civilian = "猫"
undercover = "狗"

[[pairs]]
civilian = "狮子"
undercover = "老虎"

[[pairs]]
civilian = "兔子"
undercover = "松鼠"

[[pairs]]
civilian = "熊猫"
undercover = "考拉"

[[pairs]]
civilian = "海豚"
undercover = "鲸鱼"

[[pairs]]
civilian = "乌龟"
undercover = "青蛙"

[[pairs]]
civilian = "长颈鹿"
undercover = "斑马"

[[pairs]]
civilian = "猴子"
undercover = "猩猩"

[[pairs]]
civilian = "鸽子"
undercover = "麻雀"

[[pairs]]
civilian = "金鱼"
undercover = "小孔雀鱼"

[[pairs]]
civilian = "苹果"
undercover = "梨"

[[pairs]]
civilian = "草莓"
undercover = "樱桃"

[[pairs]]
civilian = "香蕉"
undercover = "芒果"

[[pairs]]
civilian = "西瓜"
undercover = "哈密瓜"

[[pairs]]
civilian = "葡萄"
undercover = "蓝莓"

[[pairs]]
civilian = "橙子"
undercover = "柚子"

[[pairs]]
civilian = "桃子"
undercover = "李子"

[[pairs]]
civilian = "菠萝"
undercover = "凤梨"

[[pairs]]
civilian = "山楂"
undercover = "红枣"

[[pairs]]
civilian = "石榴"
undercover = "百香果"

[[pairs]]
civilian = "汉堡"
undercover = "披萨"

[[pairs]]
civilian = "米饭"
undercover = "面条"

[[pairs]]
civilian = "饺子"
undercover = "包子"

[[pairs]]
civilian = "馒头"
undercover = "花卷"

[[pairs]]
civilian = "鸡蛋"
undercover = "鹌鹑蛋"

[[pairs]]
civilian = "薯条"
undercover = "薯片"

[[pairs]]
civilian = "蛋糕"
undercover = "泡芙"

[[pairs]]
civilian = "巧克力"
undercover = "牛奶糖"

[[pairs]]
civilian = "水果冰棒"
undercover = "草莓刨冰"

[[pairs]]
civilian = "玉米"
undercover = "红薯"

[[pairs]]
civilian = "牛肉"
undercover = "猪肉"

[[pairs]]
civilian = "鸡翅"
undercover = "鸡腿"

[[pairs]]
civilian = "汤圆"
undercover = "饺子"

[[pairs]]
civilian = "咖啡"
undercover = "奶茶"

[[pairs]]
civilian = "可乐"
undercover = "雪碧"

[[pairs]]
civilian = "牛奶"
undercover = "酸奶"

[[pairs]]
civilian = "豆浆"
undercover = "豆奶"

[[pairs]]
civilian = "果汁"
undercover = "汽水"

[[pairs]]
civilian = "热水"
undercover = "温水"

[[pairs]]
civilian = "红茶"
undercover = "绿茶"

[[pairs]]
civilian = "柠檬水"
undercover = "蜂蜜水"

[[pairs]]
civilian = "椰子汁"
undercover = "杏仁露"

[[pairs]]
civilian = "草莓奶昔"
undercover = "水果冰沙"

[[pairs]]
civilian = "白酒"
undercover = "白花蛇草水"

[[pairs]]
civilian = "功夫茶"
undercover = "盖碗茶"

[[pairs]]
civilian = "春天"
undercover = "秋天"

[[pairs]]
civilian = "夏天"
undercover = "雨季"

[[pairs]]
civilian = "开学季"
undercover = "毕业季"

[[pairs]]
civilian = "开花期"
undercover = "落果期"
